# FROM registry.access.redhat.com/ubi8/ubi
FROM registry.access.redhat.com/ubi8-minimal
ARG PKG=microdnf
ARG DB=pgsql

RUN rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-latest.el8.noarch.rpm \
    && ${PKG} install zabbix-web-${DB} \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

EXPOSE 8080/TCP 8443/TCP
WORKDIR /usr/share/zabbix
COPY ["docker-entrypoint.sh", "/usr/bin/"]
USER 1997
ENTRYPOINT ["docker-entrypoint.sh"]
