all:
  hosts:
    rocky8-podman:
      hostname: rocky8-podman
      # kolla host requires 2 network interfaces
      network_interfaces:
        # - type: internal
        #   ip: 172.17.177.21
          # network_name: kollanet
        - type: private
          ip: 192.168.222.10
          # network_name: kollanet
        # - type: dhcp
        #   auto_config: false
        #   network_name: VirtualBox Host-Only Ethernet Adapter
        #   network_name: neutron_net
        - type: unassigned
          # auto_config: false
          # ip: 192.168.56.10


      ip: 192.168.222.10
      vip: 192.168.222.10

      synced_folder:
        - host: ../../
          guest: /home/vagrant/podman-practice
      provision_pre_commands:
        - "sudo dnf update -y"
        - "sudo dnf -y install podman python36"
        - "pip3 install podman-compose"
        # # - "sudo apt -y install git python3-dev libffi-dev gcc libssl-dev python3-venv libdbus-1-dev libglib2.0-dev"
        # - "python3 -m venv packstack-venv"
        # - "source packstack-venv/bin/activate && pip install -U pip && pip install ansible"
      ansible_user: vagrant
      # kolla Host machine requirements:
      # 2 network interfaces, 8GB main memory, 40GB disk space
      # https://docs.openstack.org/kolla-ansible/2023.1/user/quickstart.html#host-machine-requirements
      cpus: 2
      memory_size: 8196
      disk_size: 50GB
