# FROM registry.access.redhat.com/ubi8/ubi
FROM registry.access.redhat.com/ubi8-minimal
ARG PKG=microdnf
ARG DB=pgsql

# RUN microdnf module enable OpenIPMI
RUN rpm -Uvh https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/OpenIPMI-libs-2.0.31-3.el8.x86_64.rpm \
    https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/gdbm-libs-1.18-2.el8.x86_64.rpm \
    https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/net-snmp-libs-5.8-28.el8.x86_64.rpm
    # http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/gdbm-libs-1.18-2.el8.x86_64.rpm
# RUN rpm -ivh https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/OpenIPMI-libs-2.0.31-3.el8.x86_64.rpm
# RUN microdnf install https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/OpenIPMI-libs-2.0.31-3.el8.x86_64.rpm
RUN rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-latest.el8.noarch.rpm \
    && ${PKG} install zabbix-server-${DB} \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

EXPOSE 10051/TCP
WORKDIR /var/lib/zabbix

VOLUME ["/var/lib/zabbix/snmptraps", "/var/lib/zabbix/export"]
COPY ["docker-entrypoint.sh", "/usr/bin/"]
# ENTRYPOINT ["/usr/bin/tini", "--", "/usr/bin/docker-entrypoint.sh"]
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
USER 1997
CMD ["/usr/sbin/zabbix_server", "--foreground", "-c", "/etc/zabbix/zabbix_server.conf"]
