FROM registry.access.redhat.com/ubi8-minimal
ARG PKG=microdnf

# set prompt format
ENV PS1="(httpd)[\u@\h \W]\\$ "

# upgrade packages
RUN ${PKG} upgrade -y \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

# install epel, remi and enable dnf module php:remi-8.2
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
    && rpm -Uvh https://rpms.remirepo.net/enterprise/remi-release-8.rpm \
    && ${PKG} module enable php:remi-8.2 \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

# install httpd and php
RUN ${PKG} install -y httpd php \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

# set entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN ln -s /usr/local/bin/docker-entrypoint.sh /

# https://httpd.apache.org/docs/2.4/stopping.html#gracefulstop
STOPSIGNAL SIGWINCH
EXPOSE 80

# USER apache
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["httpd", "-DFOREGROUND"]
