# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1
apiVersion: v1
kind: Pod
metadata:
  # annotations:
  #   org.opencontainers.image.base.digest/httpd: sha256:e641b1b037ed074bf0764831a4e070a2937f6a28699c630ed5dacb2a
  #   org.opencontainers.image.base.name/httpd: registry.access.redhat.com/ubi8-minimal:latest
  creationTimestamp: "2023-11-26T17:19:08Z"
  labels:
    app: wordpress-pod
  name: wordpress-pod
spec:
  containers:
    - image: registry.local/vagrant/httpd:2.4-20240104
      # image: registry.local/root/php-fpm:8.2-20240107
      name: httpd
      ports:
        - containerPort: 80
          hostPort: 38080
      # args:
      #   - httpd
      #   - -DFOREGROUND
      volumeMounts:
        - mountPath: /etc/httpd/conf.d/90-wordpress.conf
          name: wordpress-conf
          readOnly: true
        - mountPath: /var/www/html
          name: wp-data
      resources: {}
      securityContext: {}
    - image: registry.local/vagrant/wordpress:php8.2-6.4.1-20240104
      name: wordpress
      ports:
        - containerPort: 9000
          hostPort: 39000
          protocol: TCP
      resources: {}
      securityContext: {}
      workingDir: /var/www/html/wordpress
      # args:
      #   - httpd
      #   - -DFOREGROUND
      volumeMounts:
        - mountPath: /var/www/html
          name: wp-data
      env:
        - name: WORDPRESS_DB_NAME
          value: wp
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_USER
          value: "wordpress"
        - name: WORDPRESS_DB_PASSWORD
          value: "wordpressPA$$"
    - image: registry.local/vagrant/mariadb:almalinux8-10.11
      name: mariadb
      # ports:
      # - containerPort: 3306
      #   hostPort: 3306
      resources: {}
      # securityContext: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      args:
        - mariadbd
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: "mariadbroot"
        - name: MARIADB_DATABASE
          value: wp
        - name: MARIADB_USER
          value: "wordpress"
        - name: MARIADB_PASSWORD
          value: "wordpressPA$$"
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: wp-db-volume
  hostname: wordpress-pod
  restartPolicy: Never
  volumes:
    - name: wordpress-conf
      hostPath:
        # directory location on host
        # path: /home/vagrant/container-files/php-fpm/90-php.conf
        path: /tmp/90-wordpress.conf
        type: File
    - name: wp-db-volume
      emptyDir: {}
    - name: wp-data
      emptyDir: {}
status: {}
