all:
  hosts:
    rocky8-podman:
      hostname: rocky8-podman
      box: "rockylinux/8"
      box_version: "9.0.0"
      
      cpus: 2
      memory_size: 8196
      disk_size: 50GB

      network_interfaces:
        - type: private
          ip: 192.168.222.11

      ip: 192.168.222.11
      # vip: 192.168.222.11

      vbguest:
        installer: 'centos'
        installer_options: { allow_kernel_upgrade: true }

      synced_folder:
        - host: ../../
          guest: /home/vagrant/podman-practice

      provision_pre_commands:
        - "sudo dnf update -y"
        - "sudo dnf -y install cloud-utils-growpart"
        - "sudo dnf -y install podman python36"
        - "sudo growpart /dev/sda 4"
        - "sudo xfs_growfs /dev/sda4"

      ansible_user: vagrant      
