FROM almalinux:8.8-minimal
ARG PKG=microdnf

ARG MARIADB_VERSION=10.11

# set prompt format
ENV PS1="(mariadb-server)[\u@\h \W]\\$ "

# upgrade packages
RUN ${PKG} upgrade -y \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

# set mariadb repo settings
COPY MariaDB.repo /etc/yum.repos.d/

# install mariadb-server and required packages
RUN rpm --import https://rpm.mariadb.org/RPM-GPG-KEY-MariaDB \
    && ${PKG} install MariaDB-server socat \
    && ${PKG} install epel-release \
    && ${PKG} install pwgen tzdata xz zstd \
    && rm -rf /var/cache/dnf/* \
    && ${PKG} clean all

RUN mkdir /docker-entrypoint-initdb.d

# purge and re-create /var/lib/mysql with appropriate ownership
RUN rm -rf /var/lib/mysql /etc/mysql/mariadb.conf.d/50-mysqld_safe.cnf; \
    mkdir -p /var/lib/mysql /run/mysqld; \
    chown -R mysql:mysql /var/lib/mysql /run/mysqld; \
# ensure that /run/mysqld (used for socket and lock files) is writable regardless of the UID our mysqld instance ends up having at runtime
    chmod 1777 /run/mysqld; \
# comment out a few problematic configuration values
    find /etc/mysql/ -name '*.cnf' -print0 \
        | xargs -0 grep -lZE '^(bind-address|log|user\s)' \
        | xargs -rt -0 sed -Ei 's/^(bind-address|log|user\s)/#&/'; \
# don't reverse lookup hostnames, they are usually another container
    printf "[mariadb]\nhost-cache-size=0\nskip-name-resolve\n" > /etc/mysql/mariadb.conf.d/05-skipcache.cnf; \
# Issue #327 Correct order of reading directories /etc/mysql/mariadb.conf.d before /etc/mysql/conf.d (mount-point per documentation)
    if [ -L /etc/mysql/my.cnf ]; then \
# 10.5+
        sed -i -e '/includedir/ {N;s/\(.*\)\n\(.*\)/\n\2\n\1/}' /etc/mysql/mariadb.cnf; \
    fi

# set env
ENV LANG C.UTF-8
ENV MARIADB_VERSION=${MARIADB_VERSION}

# set entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN ln -s /usr/local/bin/docker-entrypoint.sh /

USER mysql
EXPOSE 3306

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mariadbd"]